# Generated by Django 5.0.1 on 2024-01-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='alias',
            field=models.CharField(default='Anon', max_length=50),
            preserve_default=False,
        ),
    ]
